### ISSUE TITLE
Index By Key Issue After Remove

### ISSUE THREAD

**Issue by colton-vitruviusvr** [upscalebaby/generic-serializable-dictionary#13]
There is an issue with the indexByKey dictionary not updating after a remove operation that generates an IndexOutOfRangeException. If you add 2 items to the generic dictionary, and then remove them in the same order, an IndexOutOfRangeException will be triggered because the index by key dictionary is not being updated with the new index for the second item after the first is removed (second item still has index of 1 instead of 0). The dictionary values should shuffle all elements down 1 index.

Cheers,
Colton

**Comment by upscalebaby** [comment]
Thanks for opening an issue! 

I'll have some time to look at this tomorrow or the day after most likely!

**Comment by upscalebaby** [comment]
I found some time to review this and your assessment was spot on. Quite embarrassing honestly, but thankfully the fix was easy. 

This really highlights that this project needs tests asap. I have fortunately already started this work on a local branch by learning the Test Framework package so expect this in the coming week.

Thanks again for notifying me of this issue!

**Comment by colton-vitruviusvr** [comment]
No worries, I took a look at the fix and looks good to me!

Cheers,
Colton
