### ISSUE TITLE
Does not handle generic values

### ISSUE THREAD

**Issue by NoCultist** [upscalebaby/generic-serializable-dictionary#4]
Hi,
I don't know if it's a bug or it's like that by design but I seem to have a problem.
My dictionary looks like this:

`public GenericDictionary<Character.Attribute, Character.ModifierSettings> attributeModifiers;`

Where Character.Attribute is just an enum and works flawlessly while Character.ModifierSettings is a class that looks like this:

```
[System.Serializable]
public class ModifierSettings
    {
        public enum Mode
        {
            addValue,
            addPercentValue,
        }

        public Mode mode = Mode.addValue;
        public float fValue = 1;
        public float fTime = 0;
}
```

For some reason in inspector Value is displayed as unfoldable list but unfolding it does not make anything appear only rotates fold/unfold arrow. I know there might be a problem in a way I'm using it, after all I'm no pro but this is the problem I stumbled into and can't seem to find a way around for now.

Stay safe and have a nice day

**Comment by upscalebaby** [comment]
Interesting! I have some time free later today so I will start by trying to reproduce the issue and see where we'll go from there! Hopefully this can be resolved quickly, I'll keep you updated.

Thanks for supporting the project 👍

**Comment by upscalebaby** [comment]
I've reproduced the issue. The problem is that the property drawer can't currently render more complex value types such as serializable classes.

I will look into fixing this, meanwhile you can actually uncomment line number 9 in GenericDictionaryPropertyDrawer to fix the issue for you immediately (it won't render as nicely in inspector, but it will function so you can keep working on your project at least):

//[CustomPropertyDrawer(typeof(GenericDictionary<,>))]

I'll update you when I have more info, thanks again!

**Comment by upscalebaby** [comment]
A quick update for you, I have a working solution that draws the inspector nicely when the Value-type is a serializable class. I have some small quirks to work out to make it production ready but expect an update in the coming days.

Thanks again for your support!

**Comment by NoCultist** [comment]
That's great I can't wait.
